name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    timeout-minutes: 10
=======
>>>>>>> c457ee4aba3e022c80daa6a7433bb20aead96023

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

<<<<<<< HEAD
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: flake8

      - name: Run tests
        timeout-minutes: 5
        run: pytest
=======
      - name: Install pytest and flake8
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 app/
      - name: Run tests
        timeout-minutes: 5
        run: pytest tests/

>>>>>>> c457ee4aba3e022c80daa6a7433bb20aead96023
